apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: zad5
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
      requests:
        memory: "32Mi"
        cpu: "25m"
    command: ["/bin/sh", "-c"]
    args: ["while sleep 0.01; do wget -q http://php-apache/; done"]
  restartPolicy: Never
  terminationGracePeriodSeconds: 0