apiVersion: batch/v1
kind: CronJob
metadata:
  name: stepcd
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: gitops
          containers:
            - name: zad2gitops
              image: damianboguszpl66/zad2gitops
              command: [sh, -e, -c]
              args:
                - git clone https://github.com/damianboguszpl/PFSwCO_Lab10_Config.git /temp/lab10_config && find /temp/lab10_config -name '*.yaml' -exec kubectl apply -f {} \;
